aptos_version: '282f963067535043cbdb92da41ddfa05ff4c2dda'
waypoint: https://raw.githubusercontent.com/aptos-labs/aptos-previewnet/main/waypoint.txt
genesis: https://github.com/aptos-labs/aptos-previewnet/raw/main/genesis.blob?raw=true
