---
- name: Upgrade to team's latest cut
  hosts: '{{ target }}'
  gather_facts: false
  vars_files:
    - '{{ network_varfile }}'
    - '{{ node_type_varfile }}'
  roles:
    - aptos_install
    - aptos_restart
