---
- name: Ensure that the folder exists
  file:
    path: '{{ config_directory }}'
    state: directory

- name: Ensure that the folder exists
  file:
    path: '{{ config_directory }}/config'
    state: directory

- name: Pull waypoint.txt
  get_url:
    url: '{{ waypoint }}'
    dest: '{{ config_directory }}/waypoint.txt'
    mode: '0644'

- name: Pull genesis.blob
  get_url:
    url: '{{ genesis }}'
    dest: '{{config_directory }}/genesis.blob'
    mode: '0644'

- name: Ensure that the data folder does not exist
  file:
    path: '{{ config_directory }}/data'
    state: absent

- name: Copy appropriate config file
  template:
    src: '{{ node_type }}.yaml.j2'
    dest: '{{ config_directory }}/config/{{ node_type }}.yaml'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0600'
